# Generated by Django 2.2.1 on 2019-06-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.CharField(default='event', max_length=500),
        ),
    ]
