# Generated by Django 2.2.2 on 2019-06-05 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EventModel', '0002_event_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('value', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
